{{- $services := list "config" "discovery" "customers" "vets" "visits" "gateway" "admin" }}

{{- range $svc := $services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc }}-service
  labels:
    app: {{ $svc }}-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $svc }}-service
  template:
    metadata:
      labels:
        app: {{ $svc }}-service
    spec:
      containers:
        - name: {{ $svc }}
          image: {{ (index $.Values $svc).image.repository }}:{{ (index $.Values $svc).image.tag }}
          ports:
            - containerPort: {{ if eq $svc "config" }}8888{{ else if eq $svc "discovery" }}8761{{ else if eq $svc "customers" }}8081{{ else if eq $svc "visits" }}8082{{ else if eq $svc "vets" }}8083{{ else if eq $svc "gateway" }}8080{{ else }}9090{{ end }}
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
---
{{- end }}