# Config Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: phanphuc269/spring-petclinic-config-server:latest
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: dev
spec:
  type: NodePort
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30001
---
# Discovery Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      initContainers:
        - name: wait-for-config-server
          image: busybox
          command: ['sh', '-c', 'until wget -q --spider http://config-server:8888/; do echo waiting for config server; sleep 2; done;']
      containers:
        - name: discovery-server
          image: phanphuc269/spring-petclinic-discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: dev
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30002
---
# Customers Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  labels:
    app: customers-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command: ['sh', '-c', 'until wget -q --spider http://discovery-server:8761/; do echo waiting for discovery server; sleep 2; done;']
      containers:
        - name: customers-service
          image: phanphuc269/spring-petclinic-customers-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: customers-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30003
---
# Visits Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  labels:
    app: visits-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command: ['sh', '-c', 'until wget -q --spider http://discovery-server:8761/; do echo waiting for discovery server; sleep 2; done;']
      containers:
        - name: visits-service
          image: phanphuc269/spring-petclinic-visits-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: visits-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30004
---
# Vets Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  labels:
    app: vets-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command: ['sh', '-c', 'until wget -q --spider http://discovery-server:8761/; do echo waiting for discovery server; sleep 2; done;']
      containers:
        - name: vets-service
          image: phanphuc269/spring-petclinic-vets-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: vets-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30005
---
# API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command: ['sh', '-c', 'until wget -q --spider http://discovery-server:8761/; do echo waiting for discovery server; sleep 2; done;']
      containers:
        - name: api-gateway
          image: phanphuc269/spring-petclinic-api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: dev
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006
---
# Admin Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  labels:
    app: admin-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command: ['sh', '-c', 'until wget -q --spider http://discovery-server:8761/; do echo waiting for discovery server; sleep 2; done;']
      containers:
        - name: admin-server
          image: phanphuc269/spring-petclinic-admin-server:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: dev
spec:
  type: NodePort
  selector:
    app: admin-server
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30007