spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

  zipkin:
    base-url: http://zipkin.phanphuc.id.vn
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0