spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

  zipkin:
    base-url: http://zipkin.phanphuc.id.vn
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0