spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  boot:
    admin:
      ui:
        public-url: ${SPRING_BOOT_ADMIN_PUBLIC_URL}
server:
  use-forward-headers: true
  forward-headers-strategy: native
  servlet:
    context-path: /
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
  zipkin:
    base-url: http://zipkin.phanphuc.id.vn
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
