spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

server:
  use-forward-headers: true
  forward-headers-strategy: native
  servlet:
    context-path: /
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
